<?php include('server.php'); ?>
<html>
	<head><title>About Us </title>
	<link type="text/css" rel="stylesheet" href="css\index.css">
	<link type="text/css" rel="stylesheet" href="css\aboutpage.css">
	<style>
		body{
			background-repeat:no-repeat;
			background-size:100% 100%;
			background-attachment: fixed;
		}
		</style>
	</head>
	<body  background="images\bb1.jpg" >
		<!--Header part-->
	
   	<header class="h1">
		<?php if(isset($_SESSION['username'])): ?>
			<div id="d1">
				<a href="index.php"><img src="images\logo.jpg" id="i1"></a>
			</div>
		<?php else : ?>
						<div id="d1">
				<a href="index.html"><img src="images\logo.jpg" id="i1"></a>
			</div>
		<?php endif ?>
		<div class="dropdown">
			<button class="dropbtn"><h1>Hire Person</h1></button>
			<div class="dropdown-content">
	    		<a href="postproject.php">Post a Project</a>
	    		<a href="postacontest.php">Post a Contest</a>
	    		<a href="postajob.php">Post a Job</a>
			</div>
		</div>
		<div class="dropdown">
					<button class="dropbtn"><h1>Find Work</h1></button>
					<div class="dropdown-content">
			    		<a href="browseproject.php">Browse Project</a>
			    		<a href="browsecontest.php">Browse Contest</a>
			    		<a href="browsejob.php">Browse Categories</a>
					</div>
		</div>
		<a href="howitworks.php"><h2 style="color:red;">How it Works</h2></a>
		<pre>				</pre>
		
		
		<?php if(isset($_SESSION["username"])): ?>
			<h2 style="color:red;"><?php echo $_SESSION['username'] ?></h2>&nbsp;&nbsp;&nbsp;&nbsp;
			<div class="dropdown">
			<button class="dropbtn"><img src="images\loginperson.png"></img></h1></button>
			<div class="dropdown-content">
	    		<a href="changepass.php">Change Password</a>
	    		<a href="mywork.php">My Work</a>
	    		<a style="color:red"href="index.php?logout='1'">Logout</a>
			</div>
		</div>
			
			
			
			
			
		<?php endif ?>
	</header>

	<!--Header part ends here-->
		<hr>
		<br>
		<br>
		<p id="heading11">ABOUT US</p>
		<br><br>
		<h2 id="heading1"><b>WorknHire – Freelance Marketplace for India</b></h2><br>
		<div id="content">
			WorknHire.com, a product of WorknHire Technologies Pvt Ltd,  
			has been created to bridge the gap between Freelancers and Client in 
			India by bringing them under one roof. The idea of WorknHire came to us seeing 
			the demand generated by the numerous start-ups and small business 
			to find freelancers/contractors for their work and hence a customized solution 
			for the Indian market.

			Projects can be posted and found on various categories like IT & Programming, 
			Graphic Design, Content Writing, Data Entry, Finance and Sales & Marketing. 
			Creating an account, finding work or posting a project is free of cost on WorknHire.
		</div>
		<div class="footer1">
			<div class="cont11">
				<img id="imga" src="images\rahul.jpg"></img>
				<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<b>Name: </b>Rahul Sunil Varade
				<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<b>Place :  </b>Pune
				<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<b>Designation :</b>Persuing MCA in VIT PUNE.<br>
			</div>
			<div class="cont11">
				<img id="imga" src="images\shubham.jpg"></img>
				<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<b>Name: </b>Shubham Kumar
				<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<b>Place :  </b>Pune
				<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<b>Designation :</b>Persuing MCA in VIT PUNE.<br>
			</div>
		</div>
				
		<br><br><br><br><br><br>
		
		<!--Footer part-->
	
		<div class="footer">
			<br>
			<div class="container1">
				<h1>Need work done?</h1>
				<h4 id="alignl">Post your project and receive relative money from WOrKnhirE.com. Our reputation
					system will make it easy to find the perfect opportunity for your job.
					It's the simplest and safest way to get work done online.</h4>

				<h4 id="alignl">We have millions of jobs: from web design, mobile app development, virtual assistants,
					product manufacturing and graphic design. Whatever your needs, there will be a opportunity
					to get it done.</h4>
			</div>
			<div class="container1">
				<a href="aboutus.php"><button class="button1">About Us</button></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<a href="contact.php"><button class="button1">Contact Us</button></a><br>
				<h3>Developer:&nbsp;&nbsp;&nbsp;Shubham Kumar and Rahul Varade
				<br><br><br><br><br><br><br>
				<p align="center"><font color="#cc0066" size="3">copyright © 2017</font></p>

			</div>

		</div>
		
		<!--Footer part ends here-->
		
				
		
		
		
		
	</body>
</html>



	<br><br>
		
		
		